### ISSUE TITLE
Unable to catch Control-C while using wexpect

### ISSUE THREAD

**Issue by ddeel** [raczben/wexpect#20]
**Describe the bug**
The program using wexpect needs to do some final cleanup whenever the user chooses to end the program with Control-C. However, the Python code normally used for catching Control-C does not appear to work after wexpect is used.

**To Reproduce**
Steps to reproduce the behavior are as follows.
(1) Save the code below in a file called control_c.py
(2) Bring wexpect into the Python environment (pip install wexpect)
(3) Run the code using "python control_c.py"
(4) Wait for the program to output "Starting", then enter Control-C within 5 seconds. This will show the program responding to Control-C in the desired manner,
(4) Run the code again using "python control_c.py"
(5) This time, allow the program to run more than 5 seconds, until the output from a 'ping' command appears, then enter Control-C within 5 seconds. This will show the program ending abruptly, without executing the code associated with catching Control-C.

```
import signal       # Control-C handling
import sys          # Control-C handling
import time         # Delay timing

import wexpect

# Control-C handler
def signal_handler(sig, frame):
    print("\n---- Stopped with Control-C ----")
    sys.exit(0)

# Initialize Control-C catching
signal.signal(signal.SIGINT, signal_handler)

# main()
def main():
    print('Starting')
    time.sleep(5)       # Try Control-C here

    output, status = wexpect.run("ping localhost -n 1", \
                                 withexitstatus = True)
    print('ouput =', output, '\nstatus =', status)

    time.sleep(5)       # Try Control-C here
    print('Ending')

if __name__ == "__main__":
    main()
else:
    pass
```

**Expected behavior**
There is a need to be able to catch Control-C in a Python program while using wexpect, because there is no other way to make sure some final cleanup code is executed before the program ends.

**Screenshots**
None. The code provided above should demonstrate the issue.

**Environment:**
 - Windows 10 Pro Version 1903
 - Python 3.6.1
 - wexpect==2.3.9

**Additional context**
I'm hoping there's an easy fix or a reasonable work-around for this issue. (And if I'm doing something wrong, then I wouldn't mind at all if you can tell me what that is!)

**Comment by raczben** [comment]
[v3.2.0](https://github.com/raczben/wexpect/releases/tag/v3.2.0) should solve this if `WEXPECT_SPAWN_CLASS` environment variable is set to `SpawnPipe` or `SpawnSocket`:

```
export WEXPECT_SPAWN_CLASS=SpawnSocket
```

**Comment by ddeel** [comment]
Thank you, running with the Windows environment variable 'WEXPECT_SPAWN_CLASS' set to 'SpawnPipe' does allow myPython program to catch Control-C, and that is much appreciated!

Thank you also for adding the "REFACTOR" section to the wexpect README file. That helped me understand what the environment variable is for. Adding some additional documentation about how to set this environment variable would also be a good idea, but at this point I've figured it out how to set it for what I need. ('SpawnPipe' works for me, 'SpawnSocket' does not.)

Note: It is awkward that users must enter 'set WEXPECT_SPAWN_CLASS=SpawnPipe' before running the Python program. Is there any plan to remove the need to do this? Or is there a way to set this environment variable from within the Python program?

**Comment by raczben** [comment]
Thanks, for your feedback. My plan is to set `SpawnPipe` as the default class, while it become as stable as the legacy one, so I hope this unpleasant environment variable need, will be solved implicitly.

**Comment by ddeel** [comment]
Eventually setting SpawnPipe as the default sounds good to me.

We can close this Issue if you wish. (I'm not sure if I should do that, or if I should let you do it.)

**Comment by raczben** [comment]
[v4.0.0](https://github.com/raczben/wexpect/releases/tag/v4.0.0) uses `SpanwPipe` as the default spawn class.
