### ISSUE TITLE
site package wexpect.py should not auto logger with wexpect.log

### ISSUE THREAD

**Issue by goldman7911** [raczben/wexpect#23]
**Is your feature request related to a problem? Please describe.**
When working with windows server, as it is now, when you import wexpect, a log file is generate even if you don't desire it. This causes Windows Server file permission erros for users that doesn't have permission to file write.

**Describe the solution you'd like**
Log file should be generate as request

**Describe alternatives you've considered**
Comment all logger lines to avoid issues with Wi

**Additional context**
```python
logger = logging.getLogger('wexpect')
if 'dev' in __version__ :
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)
fh = logging.FileHandler('wexpect.log', 'w', 'utf-8')
formatter = logging.Formatter('%(asctime)s - %(filename)s::%(funcName)s - %(levelname)s - %>(message)s')
fh.setFormatter(formatter)
logger.addHandler(fh)

logger.info('wexpect imported; logger working')
```

**Comment by raczben** [comment]
Fixed in [v3.2.0](https://github.com/raczben/wexpect/releases/tag/v3.2.0)
