### ISSUE TITLE
unclear how to stop/kill/terminate/close the shell

### ISSUE THREAD

**Issue by nmz787** [raczben/wexpect#30]
I see several functions in the source code, but the documentation/README nor examples show what is the proper way to terminate a shell and all it's subprocesses.

Please add this to the main README, etc...

**Comment by raczben** [comment]
Yes, you're right, the lack of the documentation is still a weakness. The preferred way to terminate your child is to command your child-program to exit, then wait for `EOF`, but force termination can be done by the [terminate](https://github.com/raczben/wexpect/blob/ec3f7ea2e805e1302aa61c9b0a65ca38c1ade235/wexpect/legacy_wexpect.py#L793) method of the spawn class

**Comment by raczben** [comment]
If you still had this problem feel free to reopen.

**Comment by nmz787** [comment]
Did you update the docs?
