### ISSUE TITLE
An environment variable becomes too big and the program fails completely

### ISSUE THREAD

**Issue by ddeel** [raczben/wexpect#31]
**Describe the bug**
If a Windows Python program calls 'spawn' or 'run' too many times (with WEXPECT_SPAWN_CLASS=SpawnPipe), the program halts with an error on the console that says 'the environment variable is longer than 32767 characters'.

**To Reproduce**
Steps to reproduce the behavior are as follows.
(1) Save the code below in a file called run_check.py
(2) Bring wexpect into the Python environment (pip install wexpect)
(3) Set the WEXPECT_SPAWN_CLASS environment variable (set WEXPECT_SPAWN_CLASS=SpawnPipe)
(4) Run the code using "python run_check.py"
(5) Wait for the program to end or fail. This will likely take a few minutes, so the code includes a simple progress indicator that lets you know it is still running.

```
import wexpect

def main():
    print('---- run_check.py ----')
    for loop in range(1, 1000):
        try:
            x = wexpect.run('tasklist')
        except Exception as error:
            print('\n---- Unable to run command ----')
            print('loop =', loop, '\nerror =', error)
            exit(1)
        print('.', sep='', end='', flush=True)  # Progress indicator

if __name__ == "__main__":
    main()
else:
    pass
```

**Expected behavior**
The program should print 1,000 dot characters and then stop if the issue does not occur. If the program encounters the issue, it will print the loop number and the error.

**Screenshots**
None. The code provided above should demonstrate the issue.

**Environment:**
 - Windows 10 Pro Version 1903
 - Python 3.8.1
 - wexpect==3.3.0

**Additional context**
When I run the program with the environment variable WEXPECT_SPAWN_CLASS not set (legacy wexpect), it completes without any error. (I can't use wexpect this way because I need to be able to catch Control-C, and that means I need to set WEXPECT_SPAWN_CLASS=SpawnPipe.)

When I run the program with WEXPECT_SPAWN_CLASS=SpawnPipe, it fails after calling 'run' roughly 650 times, and the error says: "the environment variable is longer than 32767 characters".

I've seen these same results on two different Windows systems. On one system, 'loop' reaches 656 before the program fails, and on the other system 'loop' reaches 643 before the failure occurs.

Note: The program given above only calls 'run', but I've gotten exactly the same results with a longer program that uses 'spawn'/'terminate' instead of 'run'. (I thought it would be better to use the shorter program for this Issue. :-)

I'm guessing, but it's like there's an environment variable that grows by ~50 bytes every time 'run' or 'spawn' is called, and when the environment variable becomes larger than 2^15, the program stops with an error.

**Comment by raczben** [comment]
Sorry for the inactivity. 

Thank you for the detailed description, and script.

I've found that the `PYTHONPATH` grows in each call in [startChild][1] function.

[1]: https://github.com/raczben/wexpect/blob/a3acabda7315d179157ffbdf8c1f92d7c4d2c8ac/wexpect/host.py#L320

**Comment by raczben** [comment]
[v3.3.1](https://github.com/raczben/wexpect/releases/tag/v3.3.1) fixes this issue.

Upgrade your installation with:

`python -m pip install --upgrade wexpect`
