### ISSUE TITLE
Seeing weird character in interact mode

### ISSUE THREAD

**Issue by umrsrakesh** [raczben/wexpect#32]
I am trying to automate ssh terminal operations. Currently facing couple of issues 

1.  Weird character appear in console filled with ���������. I am not able to figure out what is actually present in current screen since the complete screen is filled with these characters . Is there a away to avoid these characters getting displayed
2.  neither expect method nor the realine()/readlines() read the complete console. I tried setting the window size (400,400) it did not make any difference. Also tried increasing the maxread property, did not help either
Please provide some suggestions to resolve these. Thanks in Advance!!

**Comment by raczben** [comment]
Hi,

These characters comes from wexpect's virtual terminal emulator. I don't recommend to use `interact()` mode in released codes. I use it only for debug.

Please try to use another [`screenbufferfillchar`](https://github.com/raczben/wexpect/blob/ec3f7ea2e805e1302aa61c9b0a65ca38c1ade235/wexpect/legacy_wexpect.py#L102), regarding the comment in [1539](https://github.com/raczben/wexpect/blob/ec3f7ea2e805e1302aa61c9b0a65ca38c1ade235/wexpect/legacy_wexpect.py#L1539).

**Comment by raczben** [comment]
Closing because it is not followed up. Feel free to reopen.
