### ISSUE TITLE
wexpect can't find tool command, if the env is passed as argument

### ISSUE THREAD

**Issue by ponteset** [raczben/wexpect#33]
**Problem/Request**
The feature request I want to make is due to a problem I get, when I use wexpect.spawn and give this method the prepared environment variables with the env option. I would expect that spawn will use the PATH variable which is passed as env to it. (I'm using wexpect 3.3.0 with Python 3.6.5)
```
env = os.environ.copy()
env['PATH'] += f';{os.path.dirname(self.pcfg.vivado_config.vivado)}'
os.environ['WEXPECT_SPAWN_CLASS'] = 'SpawnPipe'
from wexpect import spawn
self.proc = spawn(command=cmd, cwd=self.cwd, env=env)
```

Unfortunately it just ignores it, when it comes to the shutil.which() routine, e.g. inside the host.py. 

I would like to have that the spawn method is evaluating the environment's PATH value instead only using the PATH from system variables.

So the shutil.which command should be extended with the path argument from self.env if it is set.
```
if self.env:
    command_with_path = shutil.which(self.command, path=self.env['PATH'])
else:
    command_with_path = shutil.which(self.command)

```
**Benefits**
If you pass the env to the spawn method, you don't have to manipulate the PATH variable. Otherwise I have to manipulate the path variable which could lead to other problems.
This would be a clean solution.

**Comment by raczben** [comment]
Sorry for the late answer.
I don't want to use the env*, which is the child's environment, for the shutil's path. 
Here are two alternatives if the child's executable cannot be found in the `PATH`:
 - Add the *path* of the child's executable to the `PATH` (as you've solved) (I don't see any problem with it.)
 - Specify the child executable with full path. (In this case, shutil, will find even if your path is empty.)

\* Note, that env is unused at the moment, but it is a bug

**Comment by raczben** [comment]
I close this thread. Feel free to reopen, if it is still an issue.
