### ISSUE TITLE
Is there any child process console output limit?

### ISSUE THREAD

**Issue by nmz787** [raczben/wexpect#35]
somewhere during processing, I think around about 20000 lines of child output (hard to tell since I have expect-loop print statements interleaved in with my child output logfile), I'm getting a freeze in processing. Basically I'm running the same set of commands and expectations, but in different Python virtualenvs which the spawned shell is starting. So the same set of commands works in about 8 environments, and then freezes in the 9th. The specific command running when it gets stuck is a `pip install --editable git+https://gitlab.devserver.myhost.com/my_project/my_package.git#egg=my_package`.
I'm not sure if it's related, but I see this output a lot beforehand:
```
  Running command git fetch -q --tags
  bash: /dev/tty: No such device or address
install_pip_package expectation I==6 (child is asking for username)
   error: failed to execute prompt script (exit code 1)
my_username
  bash: /dev/tty: No such device or address
  error: failed to execute prompt script (exit code 1)
  stty: 'standard input': Inappropriate ioctl for device
```
where `install_pip_package expectation` is printed from my expect loop, showing the expectation list index, and `my_username` is the `sendline` response to the child.

So I'm wondering if I'm hitting some output buffer limit, etc...

**Comment by nmz787** [comment]
Additional info, I'm running my automation from Windows Task Scheduler... tried reproducing the issue in the command prompt, but my hope was to add a CTRL-C handler to enable interaction... but it seems the interact API has been gutted:
```
  File "my_script.py", line 466, in handler
    global_shell.interact()
AttributeError: 'SpawnPipe' object has no attribute 'interact'
```

here was my code:
```
import signal
interacting = False
def handler(signal, frame):
    global interacting
    print('welcome to the CTRL-C handler')
    if not interacting:
        interacting = True
        global_shell.interact()
    else:
        global_shell.stop_interact()
        interacting = False

signal.signal(signal.SIGINT, handler)
```

is there a new API to enable interaction? I can't seem to see anything in `host.py`

**Comment by raczben** [comment]
Sorry for the delay again.

Yes, this feature has not been migrated to new-structured wexpect. See `maxconsoleY` for more details. SpawnPipe/Socket will fail due to the lack of the `suspendThread` definition.

This is definitely a bug

**Comment by raczben** [comment]
[v3.3.1](https://github.com/raczben/wexpect/releases/tag/v3.3.1) fixes this issue.

Upgrade your installation with:

`python -m pip install --upgrade wexpect`
