### ISSUE TITLE
win32api does not contain module win32process

### ISSUE THREAD

**Issue by CGavinMullis** [raczben/wexpect#4]
In version 224 of pywin32, the function `TerminateProcess()` is no longer located in 
`win32api.win32process `
`TerminateProcess()` is now located under `win32api` and called like `win32api.TerminateProcess()`

**Comment by raczben** [comment]
Thanks CGavinMullis!
The bug has been fixed in [v2.3.5](https://github.com/raczben/wexpect/releases/tag/v2.3.5) The [test_destructor](https://github.com/raczben/wexpect/blob/master/tests/test_destructor.py) test passes now.
