### ISSUE TITLE
always get Error: no spawn class: {spawn_class_name} when import wexpect

### ISSUE THREAD

**Issue by jsplyy** [raczben/wexpect#43]
**Describe the bug**
always get Error: no spawn class: {spawn_class_name} when import wexpect

**To Reproduce**
```
    Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import wexpect
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python27\lib\site-packages\wexpect\__init__.py", line 48
        print(f'Error: no spawn class: {spawn_class_name}')
                                                         ^
    SyntaxError: invalid syntax
    >>>
```
**Expected behavior**
import wexpect without error

**Environment:**
 - [windows 10]
 - [Python 2.7.15]
 - [wexpect 4.0.0]

**Comment by raczben** [comment]
Hi,

Python 2.7 is not supported by wexpect (note, that [end of the full support of Python 2.7](https://www.python.org/doc/sunset-python-2/) )

Note, that wexpect requres Python 3.6
