### ISSUE TITLE
Fix hello_wexpect

### ISSUE THREAD

**Issue by stevemit** [raczben/wexpect#44]
It would be nice if the hello_wexpect example worked on Windows.

- There is no "ls" on Windows.
- The "dir" output contains '>' characters.

```
# run list directory command
child.sendline('dir')

# Waiting for 'C:\>' prompt
child.expect('[A-Z]\:.+>')

```

**Comment by raczben** [comment]
Have you got stuck somewhere? Do you need help?
Or. You this just a highlight to make

**Comment by stevemit** [comment]
First, thanks for this useful library!

I'm new to wexpect and I'm trying to smooth the initial experience for those coming after me, to short circuit wild guesses about what's gone wrong.  The examples should work out of the box.  It really doesn't work in IDE's (Eclipse)!  Use spawn(interact=True) to actually see a window (with funny blank characters), or use print (as in cmd_wrapper), or it's all invisible.  

A better (but complex) C:\\> prompt regexp for use with the dir output is 
`(?m)^[A-Z]\:[^<>\:\"\/\|\?\*\000-\037]+>`
The regexp I gave previously mistakes the path in "Directory of C:\\mydir" for the start of a prompt.
