### ISSUE TITLE
Can't work with windows's ssh client?

### ISSUE THREAD

**Issue by samghwww** [raczben/wexpect#45]
Can't work with windows's ssh client

**Comment by raczben** [comment]
Hi,

Please fill in all of the issue points. When you open a new issue, you get this template:

> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Environment:**
>  - [windows version]
>  - [Python version]
>  - [wexpect version]
> 
> **Additional context**
> Add any other context about the problem here.

This will help me to help you.
