### ISSUE TITLE
Regex in expect fail in W10 and Python 3.9

### ISSUE THREAD

**Issue by eirisdg** [raczben/wexpect#49]
**Describe the bug**
Regex is not working propertly when iterate lines from promt in Windows 10.

A command is sent to cmd, it is iterated, but never find EOF. Instead of this, the expect regex raises timeout.

After hour and hours spent trying to debug, i could not find the fix.

An example:
```
command = r"c:\mysql\bin\mysql_install_db.exe --service=comerzzia-mysql --password=admincmz --innodb_page_size=16K"
prompt = '[A-Za-z]\:.+>

child = wexpect.spawn('cmd.exe')
child.expect(prompt)
```
The output of this command is something like this:
```
c:\mysql\bin\mysql_install_db.exe --service=comerzzia-mysql --password=admincmz --innodb_page_size=16K
Default data directory is c:\mysql\data
Running bootstrap
2021-02-06 21:47:15 0 [Note] c:\mysql\bin\mysqld.exe (mysqld 10.4.12-MariaDB) starting as process 16012 ...
Removing default user
Setting root password
Creating my.ini file
Registering service 'comerzzia-mysql'
FATAL ERROR: CreateService failed (1073)
https://mariadb.com/kb/en/installation-issues-on-windows contains some help
for solving the most common problems.  If this doesn't help you, please
leave a comment in the Knowledge Base or file a bug report at
https://jira.mariadb.org
```

When the reader gets the last line, raises timeout, EOF is not being recogniced.

To try to fix, i've set delimiter to "prompt" value, but the regex seems to not being working well, because in the line that finds `FATAL ERROR: ` it ends.

Instead of prompt, i've tried setting delimiter as `>` and it works, but i dont think its a good solution...

**TIP**
I'm having the same issue with pexpect library. 

**Environment:**
 - Windows 10 20H2 64b
 - Python 3.9.1
 - wexpect 4.0.0

**Comment by raczben** [comment]
Hi,

1. Can you run the example script from the README with success?

```python
import wexpect

prompt = '[A-Z]\:.+>'

child = wexpect.spawn('cmd.exe')
child.expect(prompt)    # Wait for startup prompt

child.sendline('dir')   # List the current directory
child.expect(prompt)

print(child.before)     # Print the list
child.sendline('exit')
```

2. (I have not used this, `mysql_install_db`, so I don't know how should it work...) Does your program (`c:\mysql\bin\mysql_install_db.exe --service=comerzzia-mysql --password=admincmz --innodb_page_size=16K`) returns with the CMD's prompt (`C:\Your\path>`) when you run it _without_ expect? Note, that if `mysql_install_db` does not finish, and returns the prompt, wexpect won't find matching for the prompt regex.
If `mysql_install_db` does not finishes the run you have to replace the given prompt expression with `mysql_install_db`'s internal prompt.

3. Do you plan to interact with `mysql_install_db`? I mean, if you just want to run it and check the return value and the stdout, I suggest using python's built in [`subprocess.check_output`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output). (However, if you plan to send commands to it, you should use expect) (Again, I don't know `mysql_install_db`)

4. How long does `mysql_install_db` run? (wexpect default timeout is 30 sec.)

**Comment by eirisdg** [comment]
1. The example works well. The issue is with the iterator.
2. It executes a MySQL clean installation. Yes, it finish and return the prompt.
3. Interact is needed
4. 10 secs, aprox
